c = require('colors')
return {
    {
        Abilities = { 'Undulating Shockwave', },
        Spells = { },
        Users = {'Gartell', 'Leshonn'},
        Reaction = '/echo $action - Time to nuke Ice',
		Color = c.ice_blue,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Shrieking Gale', },
        Spells = { },
        Users = {'Gartell', 'Leshonn'},
        Reaction = '/echo $action - Time to nuke Stone',
		Color = c.yellow,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Flaming Kick', },
        Spells = { },
        Users = {'Degei', 'Aita'},
        Reaction = '/echo $action - Time to nuke Water',
		Color = c.blue,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Flashflood', },
        Spells = { },
        Users = {'Degei', 'Aita'},
        Reaction = '/echo $action - Time to nuke Thunder',
		Color = c.purple,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Icy Grasp', },
        Spells = { },
        Users = {'Degei', 'Aita'},
        Reaction = '/echo $action - Time to nuke Fire',
		Color = c.red,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Eroding Flesh', },
        Spells = { },
        Users = {'Degei', 'Aita'},
        Reaction = '/echo $action - Time to nuke Aero',
		Color = c.green,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Fulminous Smash', },
        Spells = { },
        Users = {'Degei', 'Aita'},
        Reaction = '/echo $action - Time to nuke Stone',
		Color = c.yellow,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Demonfire', },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo $action - Time to nuke Fire',
		Color = c.red,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Torrential Pain', },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo $action - Time to nuke Water',
		Color = c.blue,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Frozen Blood', },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo $action - Time to nuke Ice',
		Color = c.light_blue,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Ceaseless Surge', },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo $action - Time to nuke Thunder',
		Color = c.purple,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Blast of Reticence', },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo $action - Time to nuke Aero',
		Color = c.green,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Ensepulcher', },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo $action - Time to nuke Stone',
		Color = c.yellow,
        MustTargetSelf = false,
    },
    {
        Abilities = { 'Incessant Void','Bane of Tartarus' },
        Spells = { },
        Users = {'Aminon'},
        Reaction = '/echo Oh no!',
		Color = nil,
        MustTargetSelf = false,
    },
};
